[package]
name = "analyzer"
version = "0.1.0"
authors = ["Ivor Wanders <ivor@iwanders.net>"]
edition = "2018"
links = "wireshark"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.93"
lazy_static = "1.4.0"
bitflags = "1.2.1"

[lib]
name = "razer_wireshark_dissector"
path = "src/lib.rs"
crate-type = ["cdylib"]      # Creates dynamic lib

